const Grover3Qubits = (state: number) => {
  let temp = [
    {
      id: 1,
      widgets: ["×", "×", "×", "×", "×", "×", "×"],
    },
    {
      id: 2,
      widgets: ["×", "×", "×", "×", "×", "×", "×"],
    },
    {
      id: 3,
      widgets: ["×", "×", "×", "×", "×", "×", "×"],
    },
  ];

  switch (state) {
    case 0:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "X";
      temp[1].widgets[1] = "X";
      temp[2].widgets[1] = "X";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "X";
      temp[1].widgets[3] = "X";
      temp[2].widgets[3] = "X";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "X";
      temp[1].widgets[9] = "X";
      temp[2].widgets[9] = "X";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "X";
      temp[1].widgets[11] = "X";
      temp[2].widgets[11] = "X";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;
    case 1:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "X";
      temp[1].widgets[1] = "X";
      temp[2].widgets[1] = "Ident";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "X";
      temp[1].widgets[3] = "X";
      temp[2].widgets[3] = "Ident";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "X";
      temp[1].widgets[9] = "X";
      temp[2].widgets[9] = "Ident";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "X";
      temp[1].widgets[11] = "X";
      temp[2].widgets[11] = "Ident";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;
    case 2:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "X";
      temp[1].widgets[1] = "Ident";
      temp[2].widgets[1] = "X";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "X";
      temp[1].widgets[3] = "Ident";
      temp[2].widgets[3] = "X";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "X";
      temp[1].widgets[9] = "Ident";
      temp[2].widgets[9] = "X";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "X";
      temp[1].widgets[11] = "Ident";
      temp[2].widgets[11] = "X";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;
    case 3:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "X";
      temp[1].widgets[1] = "Ident";
      temp[2].widgets[1] = "Ident";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "X";
      temp[1].widgets[3] = "Ident";
      temp[2].widgets[3] = "Ident";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "X";
      temp[1].widgets[9] = "Ident";
      temp[2].widgets[9] = "Ident";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "X";
      temp[1].widgets[11] = "Ident";
      temp[2].widgets[11] = "Ident";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;

    case 4:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "Ident";
      temp[1].widgets[1] = "X";
      temp[2].widgets[1] = "X";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "Ident";
      temp[1].widgets[3] = "X";
      temp[2].widgets[3] = "X";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "Ident";
      temp[1].widgets[9] = "X";
      temp[2].widgets[9] = "X";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "Ident";
      temp[1].widgets[11] = "X";
      temp[2].widgets[11] = "X";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;

    case 5:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "Ident";
      temp[1].widgets[1] = "X";
      temp[2].widgets[1] = "Ident";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "Ident";
      temp[1].widgets[3] = "X";
      temp[2].widgets[3] = "Ident";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "Ident";
      temp[1].widgets[9] = "X";
      temp[2].widgets[9] = "Ident";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "Ident";
      temp[1].widgets[11] = "X";
      temp[2].widgets[11] = "Ident";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;

    case 6:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "Ident";
      temp[1].widgets[1] = "Ident";
      temp[2].widgets[1] = "X";
      temp[0].widgets[2] = "C-CCZ";
      temp[1].widgets[2] = "C-CCZ";
      temp[2].widgets[2] = "CCZ";
      temp[0].widgets[3] = "Ident";
      temp[1].widgets[3] = "Ident";
      temp[2].widgets[3] = "X";
      temp[0].widgets[4] = "H";
      temp[1].widgets[4] = "H";
      temp[2].widgets[4] = "H";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "C-CCZ";
      temp[1].widgets[6] = "C-CCZ";
      temp[2].widgets[6] = "CCZ";
      temp[0].widgets[7] = "X";
      temp[1].widgets[7] = "X";
      temp[2].widgets[7] = "X";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "Ident";
      temp[1].widgets[9] = "Ident";
      temp[2].widgets[9] = "X";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "Ident";
      temp[1].widgets[11] = "Ident";
      temp[2].widgets[11] = "X";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      temp[0].widgets[13] = "X";
      temp[1].widgets[13] = "X";
      temp[2].widgets[13] = "X";
      temp[0].widgets[14] = "C-CCZ";
      temp[1].widgets[14] = "C-CCZ";
      temp[2].widgets[14] = "CCZ";
      temp[0].widgets[15] = "X";
      temp[1].widgets[15] = "X";
      temp[2].widgets[15] = "X";
      temp[0].widgets[16] = "H";
      temp[1].widgets[16] = "H";
      temp[2].widgets[16] = "H";

      break;

    default:
      temp[0].widgets[0] = "H";
      temp[1].widgets[0] = "H";
      temp[2].widgets[0] = "H";
      temp[0].widgets[1] = "C-CCZ";
      temp[1].widgets[1] = "C-CCZ";
      temp[2].widgets[1] = "CCZ";
      temp[0].widgets[2] = "H";
      temp[1].widgets[2] = "H";
      temp[2].widgets[2] = "H";
      temp[0].widgets[3] = "X";
      temp[1].widgets[3] = "X";
      temp[2].widgets[3] = "X";
      temp[0].widgets[4] = "C-CCZ";
      temp[1].widgets[4] = "C-CCZ";
      temp[2].widgets[4] = "CCZ";
      temp[0].widgets[5] = "X";
      temp[1].widgets[5] = "X";
      temp[2].widgets[5] = "X";
      temp[0].widgets[6] = "H";
      temp[1].widgets[6] = "H";
      temp[2].widgets[6] = "H";
      temp[0].widgets[7] = "C-CCZ";
      temp[1].widgets[7] = "C-CCZ";
      temp[2].widgets[7] = "CCZ";
      temp[0].widgets[8] = "H";
      temp[1].widgets[8] = "H";
      temp[2].widgets[8] = "H";
      temp[0].widgets[9] = "X";
      temp[1].widgets[9] = "X";
      temp[2].widgets[9] = "X";
      temp[0].widgets[10] = "C-CCZ";
      temp[1].widgets[10] = "C-CCZ";
      temp[2].widgets[10] = "CCZ";
      temp[0].widgets[11] = "X";
      temp[1].widgets[11] = "X";
      temp[2].widgets[11] = "X";
      temp[0].widgets[12] = "H";
      temp[1].widgets[12] = "H";
      temp[2].widgets[12] = "H";
      break;
  }

  return temp;
};

export default Grover3Qubits;
